In [5]:
import numpy as np

In [2]:
a = np.array([10, 20, 30, 40])

print(a)

[10 20 30 40]


In [ ]:
#Jour5 
# Janvier | fevrier | mars
ventes = np.array([
    [1200, 1500, 1700],
    [2000, 2100, 2300],
    [900,  np.nan, 1200],
    [1800, 1900, 2000],
    [2500, 2700, np.nan],
    [1400, 1600, 1800]
])
categories = np.array([
    "A", "B", "A", "C", "B", "A"
])
#Partie 1 — Valeurs manquantes
#1
print(np.isnan(ventes))
#2
print(np.isnan(ventes).sum())
#3
print(np.nanmean(ventes))
#4
print(np.nansum(ventes))

[[False False False]
 [False False False]
 [False  True False]
 [False False False]
 [False False  True]
 [False False False]]
2
1787.5
28600.0


In [66]:
#Partie 2 :
#5
print(np.nansum(ventes,axis = 0))
#6
moyenne = (np.nanmean(ventes,axis=1)).round(2)
print(moyenne)
#Partie 3:
#7
print(np.where(moyenne>=1800,'fort','normal'))
#8
print(np.unique(categories))
#9
categorie,compter = np.unique(categories,return_counts=True)
print(categorie)
print(compter)

[9800. 9800. 9000.]
[1466.67 2133.33 1050.   1900.   2600.   1600.  ]
['normal' 'fort' 'normal' 'fort' 'fort' 'normal']
['A' 'B' 'C']
['A' 'B' 'C']
[3 2 1]


In [75]:
#Partie 4 : Assemblage
nouvelles_ventes = np.array([
    [1600, 1700, 1900],
    [2200, 2400, 2600]
])
#10
ventes_completes = np.concatenate((ventes,nouvelles_ventes))
print(ventes_completes)
#11
print(ventes_completes.shape)

#Partie 5 — split()
x = np.array([10, 20, 30, 40, 50, 60, 70, 80])
#12
print(np.split(x,4))

#Partie 6 — np.random
#13
np.random.seed(42)
matrice = np.random.randint(100,500,size=(3, 4))
print(matrice)

[[1200. 1500. 1700.]
 [2000. 2100. 2300.]
 [ 900.   nan 1200.]
 [1800. 1900. 2000.]
 [2500. 2700.   nan]
 [1400. 1600. 1800.]
 [1600. 1700. 1900.]
 [2200. 2400. 2600.]]
(8, 3)
[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]
[[202 448 370 206]
 [171 288 120 202]
 [221 314 430 187]]
